apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cp4d-install
  namespace: cp4d
spec:
  params:
    - name: version
  steps:
    - name: install
      image: registry.access.redhat.com/ubi8/ubi-minimal
      env:
        - name: IBM_ENTITLEMENT_KEY
          valueFrom:
            secretKeyRef:
              name: ibm-entitlement-key
              key: key
      script: |
        set -e
        echo "Installing required tools"
        microdnf install -y curl tar gzip

        echo "Downloading cpd-cli"
        curl -L -f -o cpd-cli.tgz https://github.com/IBM/cpd-cli/releases/v14.3.1/cpd-cli-linux-EE-14.3.1.tgz

        echo "Extracting"
        tar -xzf cpd-cli.tgz

        echo "Setting executable"
        chmod +x cpd-cli-linux-*/cpd-cli
        export PATH=$PWD/cpd-cli-linux-*/:$PATH

        echo " Verify CLI"
        cpd-cli version

        echo "Login check"
        oc whoami

        echo "Installing CP4D"
        cpd-cli manage apply-cluster-components \
          --release=$(params.version) \
          --license_acceptance=true

        cpd-cli manage apply-olm \
          --release=$(params.version)

        cpd-cli manage apply-cr \
          --components=cpd_platform \
          --release=$(params.version) \
          --namespace=cp4d \
          --block_storage_class=ocs-storagecluster-ceph-rbd \
          --file_storage_class=ocs-storagecluster-cephfs \
          --license_acceptance=true
