apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cp4d-install
  namespace: cp4d
spec:
  params:
    - name: version
  steps:
    - name: install
      image: registry.access.redhat.com/ubi8/ubi-minimal
      env:
        - name: IBM_ENTITLEMENT_KEY
          valueFrom:
            secretKeyRef:
              name: ibm-entitlement-key
              key: key
      script: |
        set -e
        echo "Installing required tools"
        microdnf install -y curl tar gzip

        echo "Downloading cpd-cli"
        curl -L -f -o cpd-cli.tgz https://github.com/IBM/cpd-cli/releases/download/v14.3.1/cpd-cli-linux-EE-14.3.1.tgz

        echo "Extracting"
        tar -xzf cpd-cli.tgz
        
        echo "Locate CLI root directory"
        CLI_ROOT=$(tar -tf cpd-cli.tgz | head -1 | cut -d/ -f1)

        echo "CLI_ROOT=$CLI_ROOT"

        echo "Copy CLI + plugins"
        cp -r $CLI_ROOT/* /usr/local/bin/

        echo "Set permissions"
        chmod +x /usr/local/bin/cpd-cli

        echo "Verify structure"
        ls -l /usr/local/bin/
        ls -l /usr/local/bin/plugins
        ls -l /usr/local/bin/LICENSES

        echo "Verify CLI"
        cpd-cli version
        
        
        echo "Downloading oc CLI (OCP 4.18)"

        curl -L -o oc.tar.gz \
        https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.18/openshift-client-linux.tar.gz
        
        echo "Validate download"
        ls -lh oc.tar.gz
        echo "File size:"
        ls -lh oc.tar.gz

        echo "Extracting oc"
        tar -xzf oc.tar.gz

        echo "Move oc to /usr/local/bin"
        mv oc kubectl /usr/local/bin/

        chmod +x /usr/local/bin/oc

        echo "Verify oc"
        oc version --client
        
        echo "Login check"
        oc whoami
        
        echo "Installing CP4D"
        cpd-cli manage apply-cluster-components \
          --release=$(params.version) \
          --license_acceptance=true

        cpd-cli manage apply-olm \
          --release=$(params.version)

        cpd-cli manage apply-cr \
          --components=cpd_platform \
          --release=$(params.version) \
          --namespace=cp4d \
          --block_storage_class=ocs-storagecluster-ceph-rbd \
          --file_storage_class=ocs-storagecluster-cephfs \
          --license_acceptance=true
