apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cp4d-setup
  namespace: cp4d
spec:
  params:
    - name: namespace
  steps:
    - name: create-ns
      image: quay.io/openshift/origin-cli
      script: |
        oc create ns $(params.namespace) || true
