apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cp4d-install-run-
  namespace: cp4d
spec:
  pipelineRef:
    name: cp4d-install-pipeline
  params:
    - name: cp4d-version
      value: "5.3.1"
    - name: namespace
      value: "cp4d"
